# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import corescript_pb2 as corescript__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in corescript_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoreScriptRunnerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteScript = channel.unary_unary(
                '/CoreScript.CoreScriptRunner/ExecuteScript',
                request_serializer=corescript__pb2.ExecuteScriptRequest.SerializeToString,
                response_deserializer=corescript__pb2.ExecuteScriptResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/CoreScript.CoreScriptRunner/GetStatus',
                request_serializer=corescript__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=corescript__pb2.GetStatusResponse.FromString,
                _registered_method=True)
        self.GetScriptMetadata = channel.unary_unary(
                '/CoreScript.CoreScriptRunner/GetScriptMetadata',
                request_serializer=corescript__pb2.GetScriptMetadataRequest.SerializeToString,
                response_deserializer=corescript__pb2.GetScriptMetadataResponse.FromString,
                _registered_method=True)
        self.GetScriptParameters = channel.unary_unary(
                '/CoreScript.CoreScriptRunner/GetScriptParameters',
                request_serializer=corescript__pb2.GetScriptParametersRequest.SerializeToString,
                response_deserializer=corescript__pb2.GetScriptParametersResponse.FromString,
                _registered_method=True)
        self.GetCombinedScript = channel.unary_unary(
                '/CoreScript.CoreScriptRunner/GetCombinedScript',
                request_serializer=corescript__pb2.GetCombinedScriptRequest.SerializeToString,
                response_deserializer=corescript__pb2.GetCombinedScriptResponse.FromString,
                _registered_method=True)
        self.GetContext = channel.unary_unary(
                '/CoreScript.CoreScriptRunner/GetContext',
                request_serializer=corescript__pb2.GetContextRequest.SerializeToString,
                response_deserializer=corescript__pb2.GetContextResponse.FromString,
                _registered_method=True)
        self.CreateAndOpenWorkspace = channel.unary_unary(
                '/CoreScript.CoreScriptRunner/CreateAndOpenWorkspace',
                request_serializer=corescript__pb2.CreateWorkspaceRequest.SerializeToString,
                response_deserializer=corescript__pb2.CreateWorkspaceResponse.FromString,
                _registered_method=True)
        self.GetScriptManifest = channel.unary_unary(
                '/CoreScript.CoreScriptRunner/GetScriptManifest',
                request_serializer=corescript__pb2.GetScriptManifestRequest.SerializeToString,
                response_deserializer=corescript__pb2.GetScriptManifestResponse.FromString,
                _registered_method=True)
        self.ValidateWorkingSet = channel.unary_unary(
                '/CoreScript.CoreScriptRunner/ValidateWorkingSet',
                request_serializer=corescript__pb2.ValidateWorkingSetRequest.SerializeToString,
                response_deserializer=corescript__pb2.ValidateWorkingSetResponse.FromString,
                _registered_method=True)
        self.ComputeParameterOptions = channel.unary_unary(
                '/CoreScript.CoreScriptRunner/ComputeParameterOptions',
                request_serializer=corescript__pb2.ComputeParameterOptionsRequest.SerializeToString,
                response_deserializer=corescript__pb2.ComputeParameterOptionsResponse.FromString,
                _registered_method=True)
        self.SelectElements = channel.unary_unary(
                '/CoreScript.CoreScriptRunner/SelectElements',
                request_serializer=corescript__pb2.SelectElementsRequest.SerializeToString,
                response_deserializer=corescript__pb2.SelectElementsResponse.FromString,
                _registered_method=True)
        self.PickObject = channel.unary_unary(
                '/CoreScript.CoreScriptRunner/PickObject',
                request_serializer=corescript__pb2.PickObjectRequest.SerializeToString,
                response_deserializer=corescript__pb2.PickObjectResponse.FromString,
                _registered_method=True)


class CoreScriptRunnerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExecuteScript(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScriptMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScriptParameters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCombinedScript(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAndOpenWorkspace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScriptManifest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateWorkingSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ComputeParameterOptions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SelectElements(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PickObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoreScriptRunnerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteScript': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteScript,
                    request_deserializer=corescript__pb2.ExecuteScriptRequest.FromString,
                    response_serializer=corescript__pb2.ExecuteScriptResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=corescript__pb2.GetStatusRequest.FromString,
                    response_serializer=corescript__pb2.GetStatusResponse.SerializeToString,
            ),
            'GetScriptMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScriptMetadata,
                    request_deserializer=corescript__pb2.GetScriptMetadataRequest.FromString,
                    response_serializer=corescript__pb2.GetScriptMetadataResponse.SerializeToString,
            ),
            'GetScriptParameters': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScriptParameters,
                    request_deserializer=corescript__pb2.GetScriptParametersRequest.FromString,
                    response_serializer=corescript__pb2.GetScriptParametersResponse.SerializeToString,
            ),
            'GetCombinedScript': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCombinedScript,
                    request_deserializer=corescript__pb2.GetCombinedScriptRequest.FromString,
                    response_serializer=corescript__pb2.GetCombinedScriptResponse.SerializeToString,
            ),
            'GetContext': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContext,
                    request_deserializer=corescript__pb2.GetContextRequest.FromString,
                    response_serializer=corescript__pb2.GetContextResponse.SerializeToString,
            ),
            'CreateAndOpenWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAndOpenWorkspace,
                    request_deserializer=corescript__pb2.CreateWorkspaceRequest.FromString,
                    response_serializer=corescript__pb2.CreateWorkspaceResponse.SerializeToString,
            ),
            'GetScriptManifest': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScriptManifest,
                    request_deserializer=corescript__pb2.GetScriptManifestRequest.FromString,
                    response_serializer=corescript__pb2.GetScriptManifestResponse.SerializeToString,
            ),
            'ValidateWorkingSet': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateWorkingSet,
                    request_deserializer=corescript__pb2.ValidateWorkingSetRequest.FromString,
                    response_serializer=corescript__pb2.ValidateWorkingSetResponse.SerializeToString,
            ),
            'ComputeParameterOptions': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeParameterOptions,
                    request_deserializer=corescript__pb2.ComputeParameterOptionsRequest.FromString,
                    response_serializer=corescript__pb2.ComputeParameterOptionsResponse.SerializeToString,
            ),
            'SelectElements': grpc.unary_unary_rpc_method_handler(
                    servicer.SelectElements,
                    request_deserializer=corescript__pb2.SelectElementsRequest.FromString,
                    response_serializer=corescript__pb2.SelectElementsResponse.SerializeToString,
            ),
            'PickObject': grpc.unary_unary_rpc_method_handler(
                    servicer.PickObject,
                    request_deserializer=corescript__pb2.PickObjectRequest.FromString,
                    response_serializer=corescript__pb2.PickObjectResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CoreScript.CoreScriptRunner', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('CoreScript.CoreScriptRunner', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoreScriptRunner(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecuteScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoreScript.CoreScriptRunner/ExecuteScript',
            corescript__pb2.ExecuteScriptRequest.SerializeToString,
            corescript__pb2.ExecuteScriptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoreScript.CoreScriptRunner/GetStatus',
            corescript__pb2.GetStatusRequest.SerializeToString,
            corescript__pb2.GetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScriptMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoreScript.CoreScriptRunner/GetScriptMetadata',
            corescript__pb2.GetScriptMetadataRequest.SerializeToString,
            corescript__pb2.GetScriptMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScriptParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoreScript.CoreScriptRunner/GetScriptParameters',
            corescript__pb2.GetScriptParametersRequest.SerializeToString,
            corescript__pb2.GetScriptParametersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCombinedScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoreScript.CoreScriptRunner/GetCombinedScript',
            corescript__pb2.GetCombinedScriptRequest.SerializeToString,
            corescript__pb2.GetCombinedScriptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoreScript.CoreScriptRunner/GetContext',
            corescript__pb2.GetContextRequest.SerializeToString,
            corescript__pb2.GetContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAndOpenWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoreScript.CoreScriptRunner/CreateAndOpenWorkspace',
            corescript__pb2.CreateWorkspaceRequest.SerializeToString,
            corescript__pb2.CreateWorkspaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScriptManifest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoreScript.CoreScriptRunner/GetScriptManifest',
            corescript__pb2.GetScriptManifestRequest.SerializeToString,
            corescript__pb2.GetScriptManifestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateWorkingSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoreScript.CoreScriptRunner/ValidateWorkingSet',
            corescript__pb2.ValidateWorkingSetRequest.SerializeToString,
            corescript__pb2.ValidateWorkingSetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ComputeParameterOptions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoreScript.CoreScriptRunner/ComputeParameterOptions',
            corescript__pb2.ComputeParameterOptionsRequest.SerializeToString,
            corescript__pb2.ComputeParameterOptionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SelectElements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoreScript.CoreScriptRunner/SelectElements',
            corescript__pb2.SelectElementsRequest.SerializeToString,
            corescript__pb2.SelectElementsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PickObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoreScript.CoreScriptRunner/PickObject',
            corescript__pb2.PickObjectRequest.SerializeToString,
            corescript__pb2.PickObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
