# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import rscript_pb2 as rscript__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in rscript_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RScriptRunnerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteScript = channel.unary_unary(
                '/RScript.RScriptRunner/ExecuteScript',
                request_serializer=rscript__pb2.ExecuteScriptRequest.SerializeToString,
                response_deserializer=rscript__pb2.ExecuteScriptResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/RScript.RScriptRunner/GetStatus',
                request_serializer=rscript__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=rscript__pb2.GetStatusResponse.FromString,
                _registered_method=True)
        self.GetScriptMetadata = channel.unary_unary(
                '/RScript.RScriptRunner/GetScriptMetadata',
                request_serializer=rscript__pb2.GetScriptMetadataRequest.SerializeToString,
                response_deserializer=rscript__pb2.GetScriptMetadataResponse.FromString,
                _registered_method=True)
        self.GetScriptParameters = channel.unary_unary(
                '/RScript.RScriptRunner/GetScriptParameters',
                request_serializer=rscript__pb2.GetScriptParametersRequest.SerializeToString,
                response_deserializer=rscript__pb2.GetScriptParametersResponse.FromString,
                _registered_method=True)
        self.GetCombinedScript = channel.unary_unary(
                '/RScript.RScriptRunner/GetCombinedScript',
                request_serializer=rscript__pb2.GetCombinedScriptRequest.SerializeToString,
                response_deserializer=rscript__pb2.GetCombinedScriptResponse.FromString,
                _registered_method=True)
        self.CreateAndOpenWorkspace = channel.unary_unary(
                '/RScript.RScriptRunner/CreateAndOpenWorkspace',
                request_serializer=rscript__pb2.CreateWorkspaceRequest.SerializeToString,
                response_deserializer=rscript__pb2.CreateWorkspaceResponse.FromString,
                _registered_method=True)


class RScriptRunnerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExecuteScript(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScriptMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScriptParameters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCombinedScript(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAndOpenWorkspace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RScriptRunnerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteScript': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteScript,
                    request_deserializer=rscript__pb2.ExecuteScriptRequest.FromString,
                    response_serializer=rscript__pb2.ExecuteScriptResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=rscript__pb2.GetStatusRequest.FromString,
                    response_serializer=rscript__pb2.GetStatusResponse.SerializeToString,
            ),
            'GetScriptMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScriptMetadata,
                    request_deserializer=rscript__pb2.GetScriptMetadataRequest.FromString,
                    response_serializer=rscript__pb2.GetScriptMetadataResponse.SerializeToString,
            ),
            'GetScriptParameters': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScriptParameters,
                    request_deserializer=rscript__pb2.GetScriptParametersRequest.FromString,
                    response_serializer=rscript__pb2.GetScriptParametersResponse.SerializeToString,
            ),
            'GetCombinedScript': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCombinedScript,
                    request_deserializer=rscript__pb2.GetCombinedScriptRequest.FromString,
                    response_serializer=rscript__pb2.GetCombinedScriptResponse.SerializeToString,
            ),
            'CreateAndOpenWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAndOpenWorkspace,
                    request_deserializer=rscript__pb2.CreateWorkspaceRequest.FromString,
                    response_serializer=rscript__pb2.CreateWorkspaceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RScript.RScriptRunner', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('RScript.RScriptRunner', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RScriptRunner(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecuteScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RScript.RScriptRunner/ExecuteScript',
            rscript__pb2.ExecuteScriptRequest.SerializeToString,
            rscript__pb2.ExecuteScriptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RScript.RScriptRunner/GetStatus',
            rscript__pb2.GetStatusRequest.SerializeToString,
            rscript__pb2.GetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScriptMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RScript.RScriptRunner/GetScriptMetadata',
            rscript__pb2.GetScriptMetadataRequest.SerializeToString,
            rscript__pb2.GetScriptMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScriptParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RScript.RScriptRunner/GetScriptParameters',
            rscript__pb2.GetScriptParametersRequest.SerializeToString,
            rscript__pb2.GetScriptParametersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCombinedScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RScript.RScriptRunner/GetCombinedScript',
            rscript__pb2.GetCombinedScriptRequest.SerializeToString,
            rscript__pb2.GetCombinedScriptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAndOpenWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RScript.RScriptRunner/CreateAndOpenWorkspace',
            rscript__pb2.CreateWorkspaceRequest.SerializeToString,
            rscript__pb2.CreateWorkspaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
